---
- name: Install samba
  ansible.builtin.apt:
    name: samba
    state: latest

- name: Create Share Directory for all user
  ansible.builtin.file:
    path: /home/share
    state: directory
    mode: 0777

- name: Create smb.conf
  ansible.builtin.template:
    src: ../../../template/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    mode: 0644
  notify: Restart_smb

- name: Manage sambd
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true
